root: ./docs
structure:
  readme: ./index.md
  summary: ./SUMMARY.md

nav:
  - Home: index.md
  - Backend Structure Overview:
      - Backend Overview: ProjectOverviewDocs/BackendStructureOverview.md
      - Backend Techstack: ProjectOverviewDocs/BackendTechstack.md
  - Postgres Tables: SchemaDocs/PostgressTables.md
  - UserAuth APIs: ApiDocs/UserAuthApis.md
  - Frontend Auth Docs:
      - Forgot Password Flow: FrontendAuthDocs/ForgotPassword.md
      - Login Flow: FrontendAuthDocs/Login.md
      - SignUp Flow: FrontendAuthDocs/Signup.md
  - Frontend ReactTanstack Queries: FrontendReactTanstackQueries/ReactQueriesForApiCalling.md
  - Frontend Routing: FrontendRouting/RoleBaseRouting.md
